### ISSUE TITLE
RFP: Admin Headless CMS

### ISSUE THREAD

**Issue by gil--** [gil--/gatsby-starter-shopifypwa#44]
Decide on admin headless cms. All 3 have Gatsby source plugins. Netlify is only 100% free but missing key ecommerce features such as scheduling, composable/modular layouts:

Netlify-CMS (Git) vs Craft CMS (Cloud/Self) vs Prismic (Cloud)

**Comment by waywardm** [comment]
Why do you need a headless cms, when the data is held in Shopify?

**Comment by gil--** [comment]
@waywardm Good Question Paul. There are a couple reasons:

- OOB Shopify Theme Customizer is not available to use for Storefront API. Having theme options such as typography, colors, enabling certain features like show related products? use flyout minicart? require accounts?, etc all become much easier if we're using a config file with a merchant-friendly interface such as netlify-cms or one of the other headless CMS

- Pages is not available to use for Storefront API. Thus we need to reimplement so that a merchant can easily add new pages with proper routing, etc. and not have to touch the code. 

- Advanced content layout such as homepage, product pages, category landing pages can be done using a headless CMS such as Contentful or Prismic. You'd specify the category, product, or page and then build your page layout using a number of special widgets/modules. Like a page builder.

These are the major reasons I'm considering various headless CMS and Netlify-CMS is definitely at the top due to it being free and not requiring a complex server installation. The major downsides are lack of scheduling, lack of internationalization, and no widget/module to make page-building experiences.

**Comment by gil--** [comment]
I've decided on Netlify CMS and will create a PR soon adding some basic functionality and will add additional functionality over time.

### Main reasons
- Free & OSS:  I'm not requiring someone to immediately pay for a tool to use this repo.
- Platform agnostic: The settings and data is written to friendly non-vendor-lock-in file formats.
- Simple & Easy: Super simple and easy to get started with and understand.
- Modular Widgets: With the recent submission of https://github.com/netlify/netlify-cms/pull/1857 I think it's finally at a state where I'm comfortable including it. Widgets/Types will allow me to add Shopify Sections-like behavior.

### Drawbacks
- Scheduling/Auto-Posting not possible. Currently, it's not possible to schedule posts to automatically go live. Not exactly a core use-case so I'm ok with sacrificing this.
- i18n support is lackluster. Compared to other headless CMS, the i18n support is lackluster.
- Netlify-CMS-Source Image: image handling is subpar imo. 

I'll look into creating a few Shopify-specific Netlify CMS components to pull in products, collections, & blog posts.
